import mysql.connector as m
import customtkinter as ctk
con = m.connect(host="localhost",user="root",passwd="student")
c=con.cursor()
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("dark-blue")

app = ctk.CTk()
app.geometry("700x500")
app.title('Database Entry')
app.grid_columnconfigure(0, weight=1)
app.grid_columnconfigure(1, weight=1)
label = ctk.CTkLabel(app,text="Welcome to Timetable Entry", font=('Arial',23))
label.grid(row=0,column=0,columnspan=3)
entry = ctk.CTkEntry(app,placeholder_text="Type in your Name",state="normal",width=280)
entry.grid(row=1,column=0,padx=30,pady=20,sticky="e")
entry1 = ctk.CTkEntry(app,placeholder_text="Type in your Code",state="normal",width=280)
entry1.grid(row=1,column=1,padx=30,pady=20,sticky="w")
label2 = ctk.CTkLabel(app,text="")
label2.grid(column=0,row=3,padx=10,pady=10,columnspan=3)
def insertval():
    name= entry.get()
    global code
    code = entry1.get()
    c.execute("USE user1")
    c.execute("CREATE TABLE IF NOT EXISTS {}(Emp_id int, Emp_name varchar(20),Gender char(1),Salary int)".format(code))
    c.execute(" INSERT INTO emp1 values({},'{}','{}',{})".format(eid,name,eg,es))
    con.commit()
    c.execute("SELECT * from {code}")
    records = c.fetchall()
    label2.configure(text=records)
    entry.delete(0, 'end')A
    entry1.delete(0, 'end')
    entry2.delete(0,'end')
    entry3.delete(0,'end')
    print("Table modified")
button = ctk.CTkButton(app, text="Enter", command=insertval)
button.grid(column=0,row=4,pady=10,padx=10,columnspan=3)
app.mainloop()
